### PR TITLE
Update library.json

### PR DESCRIPTION
**Pull request by dushyantahuja**
Update library.json to increase the version number

### CODE REVIEW

**Comment by per1234** [comment]
Since PlatformIO supports using library.properties as a library manifest file (https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#description), how about just removing library.json from the repository instead? We have clear evidence here that it is problematic to keep two separate manifest files synced.

**Comment by dushyantahuja** [comment]
That would make sense. I didn't know that PlatformIO supports the Arduino manifest as well.

**Comment by maxgerhardt** [comment]
This issue is still open and users report this to our community forums (https://community.platformio.org/t/outdated-version-for-ntpclient/16926)-- @arduino-libraries, can you take a look at this PR

**Comment by per1234** [comment]
Closed by https://github.com/arduino-libraries/NTPClient/pull/121

**Pull request closed without merging**
