### PR TITLE
Rename getRawTime to getEpochTime

### PR DESCRIPTION
**Pull request by sandeepmistry**
Related to discussion in #9.

### CODE REVIEW

**Comment by FWeinb** [comment]
I would drop `getRawTime()` all together.

**Comment by sandeepmistry** [comment]
I've pushed the changes to rename ```getRawTime``` to ```getEpochTime```.

**Comment by FWeinb** [comment]
Thanks for all your work on this!

**Comment by sandeepmistry** [comment]
@FWeinb you are welcome!

From our perspective, once the 3 PR's I've submitted are in, we are good with a 3.0 release :)

**Pull request merged**
