### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Testato**
https://github.com/arduino-libraries/NTPClient/issues/34

### CODE REVIEW

**Comment by per1234** [comment]
This should be part of https://github.com/arduino-libraries/NTPClient/pull/37, preferably done in a single commit.

**Comment by Testato** [comment]
It is not possible in my know made changes in two different file using github by browser.
But for this little changes use directly the browser, by a phone in my case, is very useful. So ofyen on github you will found this way

**Comment by per1234** [comment]
Bleh. Even though the GitHub web interface only allows you to edit one file per commit, you can easily do multiple commits per branch and thus only submit a single pull request for a change. In fact even after you submit a pull request you can commit to that branch and they are automatically added to the PR.

**Comment by Testato** [comment]
thanks for the tip ;-)

**Pull request closed without merging**
