### PR TITLE
Add authors and version fields

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by FWeinb** [comment]
I think @sandeepmistry should be added as an author too. 

@sandeepmistry Are you fine with that?

**Comment by sandeepmistry** [comment]
@FWeinb I'm fine either way :)

**Comment by ivankravets** [comment]
@FWeinb @sandeepmistry Done!

**Comment by FWeinb** [comment]
Thanks!

**Comment by ivankravets** [comment]
@FWeinb thanks!

P.S: How about to use PlatformIO for CI? Travis officially supports PlatformIO for embedded projects. See https://docs.travis-ci.com/user/integration/platformio/

**Pull request merged**
