### PR TITLE
Add end() API

### PR DESCRIPTION
**Pull request by sandeepmistry**
Related to #9.

@FWeinb please review.

### CODE REVIEW

**Comment by FWeinb** [comment]
Looks good so far but we should probably test in `update()` if the UDP connection is open to not run into strange issues when the user is calling `update()` after `end()` was called.

**Comment by sandeepmistry** [comment]
Yes, I'm looking at adding the ```begin``` API now, and wondering if we should make it a mandatory call. The [UDP class](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Udp.h) currently has no way to check if a socket is in a open state..

**Comment by FWeinb** [comment]
Thats to bad. We might want to add a boolean that indicates the state of the udp instance so we can check that in `update()`.  I would make `begin` mandatory in that case to keep us from worrying to much about it.

**Comment by sandeepmistry** [comment]
I'm closing this and pulling in the changes in #11.

**Pull request closed without merging**
